project:
  type: website

website:
  favicon: images/favicon.jpg 
  title: "THEAEONWANDERER"
  navbar:
    right:
      - text: "About" 
        file: about.qmd
      - icon: github
        href: https://github.com/theaeonwanderer
      - icon: twitter
        href: https://twitter.com/theaeonwanderer
format:
  html:
    mainfont: "Ebrima"
    theme: theme.scss
    css: styles.css



