project:
  type: website

website:
  favicon: images/about/profile_picture.png 
  title: "Abdullah Zeeshan"
  navbar:
    right:
      - text: "About" 
        file: about.qmd
      - icon: twitter
        href: https://twitter.com/theaeonwanderer
      - icon: github
        href: https://github.com/theaeonwanderer
  page-navigation: true

format:
  toc: true
