project:
  type: website

website:
  favicon: images/about/profile_picture.png 
  title: "Abdullah Zeeshan"
  navbar:
    right:
      - text: "About" 
        file: about.qmd
      - icon: github
        href: https://github.com/theaeonwanderer
format:
  html:
    theme: cosmo



